path: YOUR-PATH  # dataset root dir
train: train/images  # train images (relative to 'path')
test: test/images
val: valid/images  # val images (relative to 'path')

# Classes
names:
  0: license-plate