path: /Users/lucas/Documents/prototipagem/iot-class-project/gateway_code/dataset  # dataset root dir
train: train/images  # train images (relative to 'path')
test: test/images
val: valid/images  # val images (relative to 'path')

# Classes
names:
  0: license-plate