version: '3.4'

networks:
  prototipagemNetwork:

services:
   projetoprototipagem:
        image: ${DOCKER_REGISTRY-}projetoprototipagem
        build:
          context: .
          dockerfile: ProjetoPrototipagem/Dockerfile
        depends_on:
            - mongo
        networks:
            - prototipagemNetwork
        
   mongo:
        restart: always
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=123
        networks:
            - prototipagemNetwork  
   
   mongo-express:
        container_name: mongo-express
        image: mongo-express
        depends_on:
          - mongo
        environment:
          - ME_CONFIG_MONGODB_SERVER=PrototipagemDb
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=123
          - ME_CONFIG_BASICAUTH_USERNAME=admin
          - ME_CONFIG_BASICAUTH_PASSWORD=123
        ports:
          - '8081:8081'
        networks:
            - prototipagemNetwork