version: '3.4'

networks:
  prototipagemNetwork:

services:
   projetoprototipagem:
        image: ${DOCKER_REGISTRY-}projetoprototipagem
        build:
          context: .
          dockerfile: ProjetoPrototipagem/Dockerfile
        networks:
            - prototipagemNetwork
            